### ISSUE TITLE
Place Order at MKT

### ISSUE THREAD

**Issue by Mortgy** [ismailfer/dukascopy-api-websocket#1]
Thanks for sharing this great project.

By reading the source code, I couldn't find any documentation for placing orders at market
are you going to add it? 

Thanks in advance :)

**Comment by ismailfer** [comment]
hi Mortgy; you are right; at the moment I didn't include any example on placing orders.

I will add it soon within couple of days hopefully.

Placing of orders will be included in the class DukasStrategy

**Comment by Mortgy** [comment]
Thanks a lot 😊
I thought it would be more similar to WebSocket class ? as it could be through sending messages? 
will it have RESTful api ?

**Comment by ismailfer** [comment]
Hi Mortgy; 

I have just done an example of placing a Market Order and Limit Order; using Rest API

Refer to README for examples.

In the future I will add it to the websocket API. 

take are

Ismail

**Comment by Mortgy** [comment]
Thank you @ismailfer 😊 

is there endpoint to close the opened position ?

**Comment by ismailfer** [comment]
Yep it should be added. 

Will add it soon

**Comment by Mortgy** [comment]
@ismailfer 

can you explain how to login using the Live account ? it requires Captcha pass code, how would it work via API ?

do you have any estimations when closing positions could be added ? 😊

**Comment by ismailfer** [comment]
hi Mortgy, 

I don't have a live JForex account; so to be honest not sure how to test it.

However; I found a resource in Dukascopy site; explaining that you can disable the "Pin verification" for live trading; and that should remove this problem.

Here is the link; and also example for captcha:

https://www.dukascopy.com/wiki/en/development/get-started-api/use-jforex-sdk/live-mode

**Comment by Mortgy** [comment]
@ismailfer thank you for your response
I already whitelisted my IP but I wasn't able to get my live account connected

besides, I did the close position endpoint, I could send you a PR if you're open for contribution :)

**Comment by ismailfer** [comment]
hi Muhammad,

I have reviewed the code; and added few stuff:
- renamed the endpoints from "order" to "position" and using methods GET,POST and DELETE for get position, openPosition and closePosition respectively
- added getPosition to get detail of existing position (aka dukas order)
- added optional parameters (quantity, price, slippage) when closing position 
- refined the code

Suggested work to be done next (if you can help that will be great)
- Get list of open positions
- Get list of positions
- SetStopLossPrice for existing position
- SetTakeProfitPrice for existing position

best

Ismail.

**Comment by Mortgy** [comment]
Thanks İsmail for the updates

i'll try to work on the pending TODO's and get them ready 😊

I know my level in Java isn't very good, so please review my PR's well not to spoil anything from my side 😅
